# -*- coding: utf-8 -*-
"""Caminhao_Krusk .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WS487LUib8l4MhJAmeKRib2QJp9lX2uT

### CÉLULA 1 — Instalação e imports
"""

import networkx as nx
import matplotlib.pyplot as plt

"""### CÉLULA 2 — Upload do arquivo .txt"""

nome_arquivo = input("Digite o nome do arquivo .txt: ")
with open(nome_arquivo, "r") as arquivo:
    entrada = arquivo.read()

print("Arquivo lido com sucesso!")
print("Conteúdo:\n", entrada)

"""### CÉLULA 3 — Leitura e construção do grafo"""

valor = entrada.split()
cont = 0

ilhas = int(valor[cont]);  pontes = int(valor[cont+1]);  consultas = int(valor[cont+2])
cont += 3

G = nx.Graph()
G.add_nodes_from(range(1, ilhas + 1))

for i in range(pontes):
    orig, dest, p = int(valor[cont]), int(valor[cont+1]), int(valor[cont+2])
    cont += 3

    if orig == dest:
        print(f"Self-loop ignorado: {orig} → {orig}")
        continue

    if G.has_edge(orig, dest):
        if p > G[orig][dest]['peso']:
            G[orig][dest]['peso'] = p
    else:
        G.add_edge(orig, dest, peso=p)

lista = []
for i in range(consultas):
    x, y = int(valor[cont]), int(valor[cont+1])
    cont += 2
    lista.append((x, y))

print(f"Ilhas: {ilhas} | Pontes: {pontes} | Consultas: {consultas}")
print("Arestas:", list(G.edges(data=True)))
print("Consultas:", lista)

"""### CÉLULA 4 — Árvore Geradora Máxima Kruskal"""

agmax = nx.maximum_spanning_tree(G, weight='peso', algorithm='kruskal')

arestas_interesse = set(agmax.edges())
arestas_comuns = []

for aresta in G.edges():
    ori = aresta[0]
    des = aresta[1]

    # Verifica o sentido direto (u, v)
    sentido_direto  = (ori, des) not in arestas_interesse

    # Verifica o sentido inverso (v, u) — mesma ponte, direção oposta
    sentido_inverso = (des, ori) not in arestas_interesse

    # Só adiciona se a ponte NÃO está na AGMax em nenhum dos dois sentidos
    if sentido_direto and sentido_inverso:
        arestas_comuns.append(aresta)

print("\nArestas na Árvore Geradora Máxima (Kruskal):")
for o, d, dp in agmax.edges(data=True):
    print(f"  {o} —— {d}  peso={dp['peso']}")

"""### CÉLULA 5 — Visualização do grafo"""

pos = nx.spring_layout(G, seed=42)
edge_labels = nx.get_edge_attributes(G, 'peso')

plt.figure(figsize=(9, 6))

nx.draw_networkx_edges(G, pos,
    edgelist=arestas_comuns,
    edge_color='gray',
    alpha=0.4,
    width=2)

nx.draw_networkx_edges(G, pos,
    edgelist=list(arestas_interesse),
    edge_color='red',
    width=3)

nx.draw_networkx_nodes(G, pos, node_color='lightblue', node_size=700)
nx.draw_networkx_labels(G, pos, font_size=13, font_weight='bold')
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=10)

plt.title("Grafo do Arquipélago\nVermelho = Árvore Geradora Máxima (Kruskal)")
plt.axis('off')
plt.tight_layout()
plt.show()

"""### CÉLULA 6 — Algoritmo de Kruskal para gargalo máximo"""

def kruskal_agmax(G):

    arestas_brutas = []
    for i_orig, i_dest, dict_p in G.edges(data=True):
        peso  = dict_p['peso']
        tupla = (peso, i_orig, i_dest)
        arestas_brutas.append(tupla)

    arestas = sorted(arestas_brutas, reverse=True)

    nos  = G.nodes()
    raiz = {}
    for n in nos:
        raiz[n] = n

    def encontrar_raiz(x):
        while raiz[x] != x:
            raiz[x] = raiz[raiz[x]]
            x = raiz[x]
        return x

    agmax = []
    for peso, a, b in arestas:
        raiz_o = encontrar_raiz(a)
        raiz_d = encontrar_raiz(b)

        if raiz_o == raiz_d:
            continue

        raiz[raiz_o] = raiz_d
        agmax.append((a, b, peso))

        if len(agmax) == len(G.nodes()) - 1:
            break

    return agmax

def max_bottleneck_kruskal(G, origem, destino):

    # Caso especial: origem = destino, caminhão já está lá
    if origem == destino:
        return 0

    arestas_agmax = kruskal_agmax(G)

    if not arestas_agmax:
        return 0

    aux = nx.Graph()
    aux.add_nodes_from(G.nodes())
    for a, b, p in arestas_agmax:
        aux.add_edge(a, b, peso=p)

    if not nx.has_path(aux, origem, destino):
        return 0

    caminho = nx.shortest_path(aux, origem, destino)
    a, b    = caminho[0], caminho[1]
    gargalo = aux[a][b]['peso']

    for i in range(len(caminho) - 1):
        a, b    = caminho[i], caminho[i + 1]
        peso    = aux[a][b]['peso']
        gargalo = min(gargalo, peso)

    return gargalo

"""### CÉLULA 7 — Responder as consultas"""

respostas = []
for (x, y) in lista:
    resp = max_bottleneck_kruskal(G, x, y)
    respostas.append(resp)
    print(f"Caminhão de {x} → {y}: peso máximo = {resp}")

print("\nSaída:", ' '.join(map(str, respostas)))